### ISSUE TITLE
Browser history is doubled

### ISSUE THREAD

**Issue by chr1s1k** [rudyhuynh/use-url-search-params#4]
Hi,

recently I have started using this very useful hook but found a strange behavior when using the browser's back button.
When you modify your `params` state several times and then you try to navigate back using the browser back button, only every second attempt is correct, I mean reflected in the application.
I created a simple demo to show the behavior [https://codesandbox.io/s/delicate-lake-8todi?file=/src/App.js:915-932](https://codesandbox.io/s/delicate-lake-8todi?file=/src/App.js:915-932).

Steps to reproduce:

1. type some phrase into textfield
2. hit enter / click submit button
3. type a different phrase
4. hit enter / click submit button
5. use back button in emulated browser tab

You have to click twice to navigate back to previous phrase / state of URL.

Is this intention?

**Comment by rudyhuynh** [comment]
Thank you for report an issue. This is fixed and released at v2.3.12
